In [16]:
import numpy as np

from sklearn.datasets import load_iris

from sklearn import tree

iris = load_iris()
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [17]:
print iris.target_names

['setosa' 'versicolor' 'virginica']


In [18]:
print iris.data[0:5]

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]


In [19]:
print iris.target[0:5]

[0 0 0 0 0]


In [20]:
#for i in range(len(iris.target)):
#    print "Example %d: label %s, features %s" % (i, iris.target[i], iris.data[i])

In [21]:
test_idx = [0, 50, 100]
# training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

print test_target

[0 1 2]


In [22]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [23]:
print clf.predict(test_data)

[0 1 2]


In [24]:
# viz code
from sklearn.externals.six import StringIO
import pydot
dot_data = StringIO()
tree.export_graphviz(clf,
                    out_file=dot_data,
                    feature_names=iris.feature_names,
                    class_names=iris.target_names,
                    filled=True, rounded=True,
                    impurity=False)


In [25]:
import os
os.environ["PATH"] += os.pathsep + r'C:\ProgramData\Anaconda2\pkgs\graphviz-2.38-h308b129_2\Library\bin\graphviz'

graph = pydot.graph_from_dot_data(dot_data.getvalue())
graph[0].write_pdf("iris.pdf")